// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/sds.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypeDefinition struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Id            uint32                          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Fingerprint   []byte                          `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Descriptors   *descriptorpb.FileDescriptorSet `protobuf:"bytes,4,opt,name=descriptors,proto3" json:"descriptors,omitempty"`
	KeyFields     []int32                         `protobuf:"varint,5,rep,packed,name=key_fields,json=keyFields,proto3" json:"key_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeDefinition) Reset() {
	*x = TypeDefinition{}
	mi := &file_proto_sds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeDefinition) ProtoMessage() {}

func (x *TypeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeDefinition.ProtoReflect.Descriptor instead.
func (*TypeDefinition) Descriptor() ([]byte, []int) {
	return file_proto_sds_proto_rawDescGZIP(), []int{0}
}

func (x *TypeDefinition) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TypeDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeDefinition) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *TypeDefinition) GetDescriptors() *descriptorpb.FileDescriptorSet {
	if x != nil {
		return x.Descriptors
	}
	return nil
}

func (x *TypeDefinition) GetKeyFields() []int32 {
	if x != nil {
		return x.KeyFields
	}
	return nil
}

type TxCommit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          uint64                 `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	CommitTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxCommit) Reset() {
	*x = TxCommit{}
	mi := &file_proto_sds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxCommit) ProtoMessage() {}

func (x *TxCommit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxCommit.ProtoReflect.Descriptor instead.
func (*TxCommit) Descriptor() ([]byte, []int) {
	return file_proto_sds_proto_rawDescGZIP(), []int{1}
}

func (x *TxCommit) GetTxId() uint64 {
	if x != nil {
		return x.TxId
	}
	return 0
}

func (x *TxCommit) GetCommitTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CommitTime
	}
	return nil
}

type SnapshotPointer struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Position            uint64                 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	Format              string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Location            string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	RegistryFingerprint []byte                 `protobuf:"bytes,4,opt,name=registry_fingerprint,json=registryFingerprint,proto3" json:"registry_fingerprint,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SnapshotPointer) Reset() {
	*x = SnapshotPointer{}
	mi := &file_proto_sds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotPointer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotPointer) ProtoMessage() {}

func (x *SnapshotPointer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotPointer.ProtoReflect.Descriptor instead.
func (*SnapshotPointer) Descriptor() ([]byte, []int) {
	return file_proto_sds_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotPointer) GetPosition() uint64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *SnapshotPointer) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *SnapshotPointer) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *SnapshotPointer) GetRegistryFingerprint() []byte {
	if x != nil {
		return x.RegistryFingerprint
	}
	return nil
}

type Registry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*TypeDefinition      `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_proto_sds_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sds_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_proto_sds_proto_rawDescGZIP(), []int{3}
}

func (x *Registry) GetTypes() []*TypeDefinition {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_proto_sds_proto protoreflect.FileDescriptor

const file_proto_sds_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/sds.proto\x12\x06sds.v1\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n" +
	"\x0eTypeDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vfingerprint\x18\x03 \x01(\fR\vfingerprint\x12D\n" +
	"\vdescriptors\x18\x04 \x01(\v2\".google.protobuf.FileDescriptorSetR\vdescriptors\x12\x1d\n" +
	"\n" +
	"key_fields\x18\x05 \x03(\x05R\tkeyFields\"\\\n" +
	"\bTxCommit\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\x04R\x04txId\x12;\n" +
	"\vcommit_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"commitTime\"\x94\x01\n" +
	"\x0fSnapshotPointer\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x04R\bposition\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x121\n" +
	"\x14registry_fingerprint\x18\x04 \x01(\fR\x13registryFingerprint\"8\n" +
	"\bRegistry\x12,\n" +
	"\x05types\x18\x01 \x03(\v2\x16.sds.v1.TypeDefinitionR\x05typesB:Z8github.com/gke-labs/in-cluster-storage/pkg/api/sds/v1;v1b\x06proto3"

var (
	file_proto_sds_proto_rawDescOnce sync.Once
	file_proto_sds_proto_rawDescData []byte
)

func file_proto_sds_proto_rawDescGZIP() []byte {
	file_proto_sds_proto_rawDescOnce.Do(func() {
		file_proto_sds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sds_proto_rawDesc), len(file_proto_sds_proto_rawDesc)))
	})
	return file_proto_sds_proto_rawDescData
}

var file_proto_sds_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_sds_proto_goTypes = []any{
	(*TypeDefinition)(nil),                 // 0: sds.v1.TypeDefinition
	(*TxCommit)(nil),                       // 1: sds.v1.TxCommit
	(*SnapshotPointer)(nil),                // 2: sds.v1.SnapshotPointer
	(*Registry)(nil),                       // 3: sds.v1.Registry
	(*descriptorpb.FileDescriptorSet)(nil), // 4: google.protobuf.FileDescriptorSet
	(*timestamppb.Timestamp)(nil),          // 5: google.protobuf.Timestamp
}
var file_proto_sds_proto_depIdxs = []int32{
	4, // 0: sds.v1.TypeDefinition.descriptors:type_name -> google.protobuf.FileDescriptorSet
	5, // 1: sds.v1.TxCommit.commit_time:type_name -> google.protobuf.Timestamp
	0, // 2: sds.v1.Registry.types:type_name -> sds.v1.TypeDefinition
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_sds_proto_init() }
func file_proto_sds_proto_init() {
	if File_proto_sds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sds_proto_rawDesc), len(file_proto_sds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sds_proto_goTypes,
		DependencyIndexes: file_proto_sds_proto_depIdxs,
		MessageInfos:      file_proto_sds_proto_msgTypes,
	}.Build()
	File_proto_sds_proto = out.File
	file_proto_sds_proto_goTypes = nil
	file_proto_sds_proto_depIdxs = nil
}
