// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/wal.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AppendRequest_Hello
	//	*AppendRequest_Record
	Msg           isAppendRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_proto_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{0}
}

func (x *AppendRequest) GetMsg() isAppendRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AppendRequest) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*AppendRequest_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AppendRequest) GetRecord() *AppendRecord {
	if x != nil {
		if x, ok := x.Msg.(*AppendRequest_Record); ok {
			return x.Record
		}
	}
	return nil
}

type isAppendRequest_Msg interface {
	isAppendRequest_Msg()
}

type AppendRequest_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AppendRequest_Record struct {
	Record *AppendRecord `protobuf:"bytes,2,opt,name=record,proto3,oneof"`
}

func (*AppendRequest_Hello) isAppendRequest_Msg() {}

func (*AppendRequest_Record) isAppendRequest_Msg() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      []byte                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_wal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetStreamId() []byte {
	if x != nil {
		return x.StreamId
	}
	return nil
}

type AppendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AppendResponse_HelloAck
	//	*AppendResponse_Ack
	Msg           isAppendResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_proto_wal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{2}
}

func (x *AppendResponse) GetMsg() isAppendResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AppendResponse) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Msg.(*AppendResponse_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *AppendResponse) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Msg.(*AppendResponse_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isAppendResponse_Msg interface {
	isAppendResponse_Msg()
}

type AppendResponse_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type AppendResponse_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*AppendResponse_HelloAck) isAppendResponse_Msg() {}

func (*AppendResponse_Ack) isAppendResponse_Msg() {}

type HelloAck struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	WitnessAckedStreamSeq uint64                 `protobuf:"varint,1,opt,name=witness_acked_stream_seq,json=witnessAckedStreamSeq,proto3" json:"witness_acked_stream_seq,omitempty"` // what the service has on local disk
	S3AckedStreamSeq      uint64                 `protobuf:"varint,2,opt,name=s3_acked_stream_seq,json=s3AckedStreamSeq,proto3" json:"s3_acked_stream_seq,omitempty"`                // permanent object storage watermark
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_proto_wal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{3}
}

func (x *HelloAck) GetWitnessAckedStreamSeq() uint64 {
	if x != nil {
		return x.WitnessAckedStreamSeq
	}
	return 0
}

func (x *HelloAck) GetS3AckedStreamSeq() uint64 {
	if x != nil {
		return x.S3AckedStreamSeq
	}
	return 0
}

type AppendRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamSeq     uint64                 `protobuf:"varint,1,opt,name=stream_seq,json=streamSeq,proto3" json:"stream_seq,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Crc32C        uint32                 `protobuf:"varint,3,opt,name=crc32c,proto3" json:"crc32c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRecord) Reset() {
	*x = AppendRecord{}
	mi := &file_proto_wal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRecord) ProtoMessage() {}

func (x *AppendRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRecord.ProtoReflect.Descriptor instead.
func (*AppendRecord) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{4}
}

func (x *AppendRecord) GetStreamSeq() uint64 {
	if x != nil {
		return x.StreamSeq
	}
	return 0
}

func (x *AppendRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AppendRecord) GetCrc32C() uint32 {
	if x != nil {
		return x.Crc32C
	}
	return 0
}

type Ack struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	WitnessAckedStreamSeq uint64                 `protobuf:"varint,1,opt,name=witness_acked_stream_seq,json=witnessAckedStreamSeq,proto3" json:"witness_acked_stream_seq,omitempty"` // cumulative
	S3AckedStreamSeq      uint64                 `protobuf:"varint,2,opt,name=s3_acked_stream_seq,json=s3AckedStreamSeq,proto3" json:"s3_acked_stream_seq,omitempty"`                // cumulative
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_wal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetWitnessAckedStreamSeq() uint64 {
	if x != nil {
		return x.WitnessAckedStreamSeq
	}
	return 0
}

func (x *Ack) GetS3AckedStreamSeq() uint64 {
	if x != nil {
		return x.S3AckedStreamSeq
	}
	return 0
}

type FlushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRequest) Reset() {
	*x = FlushRequest{}
	mi := &file_proto_wal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRequest) ProtoMessage() {}

func (x *FlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRequest.ProtoReflect.Descriptor instead.
func (*FlushRequest) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{6}
}

type FlushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastPosition  uint64                 `protobuf:"varint,1,opt,name=last_position,json=lastPosition,proto3" json:"last_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushResponse) Reset() {
	*x = FlushResponse{}
	mi := &file_proto_wal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushResponse) ProtoMessage() {}

func (x *FlushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushResponse.ProtoReflect.Descriptor instead.
func (*FlushResponse) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{7}
}

func (x *FlushResponse) GetLastPosition() uint64 {
	if x != nil {
		return x.LastPosition
	}
	return 0
}

type TailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPosition  uint64                 `protobuf:"varint,1,opt,name=from_position,json=fromPosition,proto3" json:"from_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailRequest) Reset() {
	*x = TailRequest{}
	mi := &file_proto_wal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailRequest) ProtoMessage() {}

func (x *TailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailRequest.ProtoReflect.Descriptor instead.
func (*TailRequest) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{8}
}

func (x *TailRequest) GetFromPosition() uint64 {
	if x != nil {
		return x.FromPosition
	}
	return 0
}

type LogRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      uint64                 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	StreamId      []byte                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	StreamSeq     uint64                 `protobuf:"varint,3,opt,name=stream_seq,json=streamSeq,proto3" json:"stream_seq,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Crc32C        uint32                 `protobuf:"varint,5,opt,name=crc32c,proto3" json:"crc32c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_proto_wal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{9}
}

func (x *LogRecord) GetPosition() uint64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *LogRecord) GetStreamId() []byte {
	if x != nil {
		return x.StreamId
	}
	return nil
}

func (x *LogRecord) GetStreamSeq() uint64 {
	if x != nil {
		return x.StreamSeq
	}
	return 0
}

func (x *LogRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LogRecord) GetCrc32C() uint32 {
	if x != nil {
		return x.Crc32C
	}
	return 0
}

type TailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *LogRecord             `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	ResumedFrom   uint64                 `protobuf:"varint,2,opt,name=resumed_from,json=resumedFrom,proto3" json:"resumed_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailResponse) Reset() {
	*x = TailResponse{}
	mi := &file_proto_wal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailResponse) ProtoMessage() {}

func (x *TailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailResponse.ProtoReflect.Descriptor instead.
func (*TailResponse) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{10}
}

func (x *TailResponse) GetRecord() *LogRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *TailResponse) GetResumedFrom() uint64 {
	if x != nil {
		return x.ResumedFrom
	}
	return 0
}

var File_proto_wal_proto protoreflect.FileDescriptor

const file_proto_wal_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/wal.proto\x12\fwal.v1alpha1\"y\n" +
	"\rAppendRequest\x12+\n" +
	"\x05hello\x18\x01 \x01(\v2\x13.wal.v1alpha1.HelloH\x00R\x05hello\x124\n" +
	"\x06record\x18\x02 \x01(\v2\x1a.wal.v1alpha1.AppendRecordH\x00R\x06recordB\x05\n" +
	"\x03msg\"$\n" +
	"\x05Hello\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\fR\bstreamId\"u\n" +
	"\x0eAppendResponse\x125\n" +
	"\thello_ack\x18\x01 \x01(\v2\x16.wal.v1alpha1.HelloAckH\x00R\bhelloAck\x12%\n" +
	"\x03ack\x18\x02 \x01(\v2\x11.wal.v1alpha1.AckH\x00R\x03ackB\x05\n" +
	"\x03msg\"r\n" +
	"\bHelloAck\x127\n" +
	"\x18witness_acked_stream_seq\x18\x01 \x01(\x04R\x15witnessAckedStreamSeq\x12-\n" +
	"\x13s3_acked_stream_seq\x18\x02 \x01(\x04R\x10s3AckedStreamSeq\"_\n" +
	"\fAppendRecord\x12\x1d\n" +
	"\n" +
	"stream_seq\x18\x01 \x01(\x04R\tstreamSeq\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x16\n" +
	"\x06crc32c\x18\x03 \x01(\rR\x06crc32c\"m\n" +
	"\x03Ack\x127\n" +
	"\x18witness_acked_stream_seq\x18\x01 \x01(\x04R\x15witnessAckedStreamSeq\x12-\n" +
	"\x13s3_acked_stream_seq\x18\x02 \x01(\x04R\x10s3AckedStreamSeq\"\x0e\n" +
	"\fFlushRequest\"4\n" +
	"\rFlushResponse\x12#\n" +
	"\rlast_position\x18\x01 \x01(\x04R\flastPosition\"2\n" +
	"\vTailRequest\x12#\n" +
	"\rfrom_position\x18\x01 \x01(\x04R\ffromPosition\"\x95\x01\n" +
	"\tLogRecord\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x04R\bposition\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\fR\bstreamId\x12\x1d\n" +
	"\n" +
	"stream_seq\x18\x03 \x01(\x04R\tstreamSeq\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x16\n" +
	"\x06crc32c\x18\x05 \x01(\rR\x06crc32c\"b\n" +
	"\fTailResponse\x12/\n" +
	"\x06record\x18\x01 \x01(\v2\x17.wal.v1alpha1.LogRecordR\x06record\x12!\n" +
	"\fresumed_from\x18\x02 \x01(\x04R\vresumedFrom2\xd7\x01\n" +
	"\tWalBuffer\x12G\n" +
	"\x06Append\x12\x1b.wal.v1alpha1.AppendRequest\x1a\x1c.wal.v1alpha1.AppendResponse(\x010\x01\x12@\n" +
	"\x05Flush\x12\x1a.wal.v1alpha1.FlushRequest\x1a\x1b.wal.v1alpha1.FlushResponse\x12?\n" +
	"\x04Tail\x12\x19.wal.v1alpha1.TailRequest\x1a\x1a.wal.v1alpha1.TailResponse0\x01BFZDgithub.com/gke-labs/in-cluster-storage/pkg/api/wal/v1alpha1;v1alpha1b\x06proto3"

var (
	file_proto_wal_proto_rawDescOnce sync.Once
	file_proto_wal_proto_rawDescData []byte
)

func file_proto_wal_proto_rawDescGZIP() []byte {
	file_proto_wal_proto_rawDescOnce.Do(func() {
		file_proto_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wal_proto_rawDesc), len(file_proto_wal_proto_rawDesc)))
	})
	return file_proto_wal_proto_rawDescData
}

var file_proto_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_wal_proto_goTypes = []any{
	(*AppendRequest)(nil),  // 0: wal.v1alpha1.AppendRequest
	(*Hello)(nil),          // 1: wal.v1alpha1.Hello
	(*AppendResponse)(nil), // 2: wal.v1alpha1.AppendResponse
	(*HelloAck)(nil),       // 3: wal.v1alpha1.HelloAck
	(*AppendRecord)(nil),   // 4: wal.v1alpha1.AppendRecord
	(*Ack)(nil),            // 5: wal.v1alpha1.Ack
	(*FlushRequest)(nil),   // 6: wal.v1alpha1.FlushRequest
	(*FlushResponse)(nil),  // 7: wal.v1alpha1.FlushResponse
	(*TailRequest)(nil),    // 8: wal.v1alpha1.TailRequest
	(*LogRecord)(nil),      // 9: wal.v1alpha1.LogRecord
	(*TailResponse)(nil),   // 10: wal.v1alpha1.TailResponse
}
var file_proto_wal_proto_depIdxs = []int32{
	1,  // 0: wal.v1alpha1.AppendRequest.hello:type_name -> wal.v1alpha1.Hello
	4,  // 1: wal.v1alpha1.AppendRequest.record:type_name -> wal.v1alpha1.AppendRecord
	3,  // 2: wal.v1alpha1.AppendResponse.hello_ack:type_name -> wal.v1alpha1.HelloAck
	5,  // 3: wal.v1alpha1.AppendResponse.ack:type_name -> wal.v1alpha1.Ack
	9,  // 4: wal.v1alpha1.TailResponse.record:type_name -> wal.v1alpha1.LogRecord
	0,  // 5: wal.v1alpha1.WalBuffer.Append:input_type -> wal.v1alpha1.AppendRequest
	6,  // 6: wal.v1alpha1.WalBuffer.Flush:input_type -> wal.v1alpha1.FlushRequest
	8,  // 7: wal.v1alpha1.WalBuffer.Tail:input_type -> wal.v1alpha1.TailRequest
	2,  // 8: wal.v1alpha1.WalBuffer.Append:output_type -> wal.v1alpha1.AppendResponse
	7,  // 9: wal.v1alpha1.WalBuffer.Flush:output_type -> wal.v1alpha1.FlushResponse
	10, // 10: wal.v1alpha1.WalBuffer.Tail:output_type -> wal.v1alpha1.TailResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_wal_proto_init() }
func file_proto_wal_proto_init() {
	if File_proto_wal_proto != nil {
		return
	}
	file_proto_wal_proto_msgTypes[0].OneofWrappers = []any{
		(*AppendRequest_Hello)(nil),
		(*AppendRequest_Record)(nil),
	}
	file_proto_wal_proto_msgTypes[2].OneofWrappers = []any{
		(*AppendResponse_HelloAck)(nil),
		(*AppendResponse_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wal_proto_rawDesc), len(file_proto_wal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wal_proto_goTypes,
		DependencyIndexes: file_proto_wal_proto_depIdxs,
		MessageInfos:      file_proto_wal_proto_msgTypes,
	}.Build()
	File_proto_wal_proto = out.File
	file_proto_wal_proto_goTypes = nil
	file_proto_wal_proto_depIdxs = nil
}
