// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/wal.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalBuffer_Append_FullMethodName = "/wal.v1alpha1.WalBuffer/Append"
	WalBuffer_Flush_FullMethodName  = "/wal.v1alpha1.WalBuffer/Flush"
	WalBuffer_Tail_FullMethodName   = "/wal.v1alpha1.WalBuffer/Tail"
)

// WalBufferClient is the client API for WalBuffer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalBufferClient interface {
	// One bidi stream per client stream. First message must be Hello.
	Append(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AppendRequest, AppendResponse], error)
	// Force a flush to permanent object storage now. Returns once the segment is durable.
	Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error)
	// Read merged records in position order. Positions are strictly increasing within a witness incarnation;
	// positions above the last flushed position are provisional and may be reassigned
	// after a restart. Tail clamps from_position to last_flushed_position + 1 when it exceeds that, returning
	// the effective start in resumed_from on the first response. Consumers must deduplicate on (stream_id, stream_seq)
	// and must tolerate re-delivery from the last flushed position after reconnecting.
	Tail(ctx context.Context, in *TailRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TailResponse], error)
}

type walBufferClient struct {
	cc grpc.ClientConnInterface
}

func NewWalBufferClient(cc grpc.ClientConnInterface) WalBufferClient {
	return &walBufferClient{cc}
}

func (c *walBufferClient) Append(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AppendRequest, AppendResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WalBuffer_ServiceDesc.Streams[0], WalBuffer_Append_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AppendRequest, AppendResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalBuffer_AppendClient = grpc.BidiStreamingClient[AppendRequest, AppendResponse]

func (c *walBufferClient) Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushResponse)
	err := c.cc.Invoke(ctx, WalBuffer_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walBufferClient) Tail(ctx context.Context, in *TailRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TailResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WalBuffer_ServiceDesc.Streams[1], WalBuffer_Tail_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TailRequest, TailResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalBuffer_TailClient = grpc.ServerStreamingClient[TailResponse]

// WalBufferServer is the server API for WalBuffer service.
// All implementations must embed UnimplementedWalBufferServer
// for forward compatibility.
type WalBufferServer interface {
	// One bidi stream per client stream. First message must be Hello.
	Append(grpc.BidiStreamingServer[AppendRequest, AppendResponse]) error
	// Force a flush to permanent object storage now. Returns once the segment is durable.
	Flush(context.Context, *FlushRequest) (*FlushResponse, error)
	// Read merged records in position order. Positions are strictly increasing within a witness incarnation;
	// positions above the last flushed position are provisional and may be reassigned
	// after a restart. Tail clamps from_position to last_flushed_position + 1 when it exceeds that, returning
	// the effective start in resumed_from on the first response. Consumers must deduplicate on (stream_id, stream_seq)
	// and must tolerate re-delivery from the last flushed position after reconnecting.
	Tail(*TailRequest, grpc.ServerStreamingServer[TailResponse]) error
	mustEmbedUnimplementedWalBufferServer()
}

// UnimplementedWalBufferServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalBufferServer struct{}

func (UnimplementedWalBufferServer) Append(grpc.BidiStreamingServer[AppendRequest, AppendResponse]) error {
	return status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedWalBufferServer) Flush(context.Context, *FlushRequest) (*FlushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedWalBufferServer) Tail(*TailRequest, grpc.ServerStreamingServer[TailResponse]) error {
	return status.Error(codes.Unimplemented, "method Tail not implemented")
}
func (UnimplementedWalBufferServer) mustEmbedUnimplementedWalBufferServer() {}
func (UnimplementedWalBufferServer) testEmbeddedByValue()                   {}

// UnsafeWalBufferServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalBufferServer will
// result in compilation errors.
type UnsafeWalBufferServer interface {
	mustEmbedUnimplementedWalBufferServer()
}

func RegisterWalBufferServer(s grpc.ServiceRegistrar, srv WalBufferServer) {
	// If the following call panics, it indicates UnimplementedWalBufferServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalBuffer_ServiceDesc, srv)
}

func _WalBuffer_Append_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WalBufferServer).Append(&grpc.GenericServerStream[AppendRequest, AppendResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalBuffer_AppendServer = grpc.BidiStreamingServer[AppendRequest, AppendResponse]

func _WalBuffer_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalBufferServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalBuffer_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalBufferServer).Flush(ctx, req.(*FlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalBuffer_Tail_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TailRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WalBufferServer).Tail(m, &grpc.GenericServerStream[TailRequest, TailResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalBuffer_TailServer = grpc.ServerStreamingServer[TailResponse]

// WalBuffer_ServiceDesc is the grpc.ServiceDesc for WalBuffer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalBuffer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wal.v1alpha1.WalBuffer",
	HandlerType: (*WalBufferServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Flush",
			Handler:    _WalBuffer_Flush_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Append",
			Handler:       _WalBuffer_Append_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Tail",
			Handler:       _WalBuffer_Tail_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/wal.proto",
}
